// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/event_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/event_service.go -destination=internal/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/mohamedelhefni/siraaj/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
	isgomock struct{}
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// GetEvents mocks base method.
func (m *MockEventService) GetEvents(startDate, endDate time.Time, limit, offset int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvents", startDate, endDate, limit, offset)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvents indicates an expected call of GetEvents.
func (mr *MockEventServiceMockRecorder) GetEvents(startDate, endDate, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvents", reflect.TypeOf((*MockEventService)(nil).GetEvents), startDate, endDate, limit, offset)
}

// GetOnlineUsers mocks base method.
func (m *MockEventService) GetOnlineUsers(timeWindow int) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnlineUsers", timeWindow)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnlineUsers indicates an expected call of GetOnlineUsers.
func (mr *MockEventServiceMockRecorder) GetOnlineUsers(timeWindow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnlineUsers", reflect.TypeOf((*MockEventService)(nil).GetOnlineUsers), timeWindow)
}

// GetProjects mocks base method.
func (m *MockEventService) GetProjects() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjects")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjects indicates an expected call of GetProjects.
func (mr *MockEventServiceMockRecorder) GetProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjects", reflect.TypeOf((*MockEventService)(nil).GetProjects))
}

// GetStats mocks base method.
func (m *MockEventService) GetStats(startDate, endDate time.Time, limit int, filters map[string]string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", startDate, endDate, limit, filters)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEventServiceMockRecorder) GetStats(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEventService)(nil).GetStats), startDate, endDate, limit, filters)
}

// GetTopProperties mocks base method.
func (m *MockEventService) GetTopProperties(startDate, endDate time.Time, limit int, filters map[string]string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopProperties", startDate, endDate, limit, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopProperties indicates an expected call of GetTopProperties.
func (mr *MockEventServiceMockRecorder) GetTopProperties(startDate, endDate, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopProperties", reflect.TypeOf((*MockEventService)(nil).GetTopProperties), startDate, endDate, limit, filters)
}

// TrackEvent mocks base method.
func (m *MockEventService) TrackEvent(event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEvent indicates an expected call of TrackEvent.
func (mr *MockEventServiceMockRecorder) TrackEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEvent", reflect.TypeOf((*MockEventService)(nil).TrackEvent), event)
}

// TrackEventBatch mocks base method.
func (m *MockEventService) TrackEventBatch(events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEventBatch", events)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEventBatch indicates an expected call of TrackEventBatch.
func (mr *MockEventServiceMockRecorder) TrackEventBatch(events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEventBatch", reflect.TypeOf((*MockEventService)(nil).TrackEventBatch), events)
}
